name: MnC_SERVER_MOD
main: me.MnC.MnC_SERVER_MOD.MnC_SERVER_MOD
version: 1.5.0 beta
authors: [rikub, hawkeye, Guga]
commands:
    who:
        description: Gets Names of Online players
    help:
        description: Prints all possible commands
    motd:
        description: Prints the current Message of the Day 
    getcoords:
        description: Prints coordinates of target block
    login:
        description: Logs a player
    register:
        description: Registers a new player
    logout:
        description: Logs a player out
    locker:
        description: Info about how to lock or unlock chest
    lock:
        description: Locks targeted chest 
    unlock:
        description: Unlocks targeted chest 
    lmod:
        description: Modifies a chest lock
    y:
        description: Confirms an action
    rpg:
        description: RPG menu
    arena:
        description: Arena menu
    gm:
        description: GM Commands menu
    helper:
        description: Command for helpers
    debug:
        description: Toggle debug
    shop:
        description: Shop Menu
    vip:
        description: Vip Menu
    places:
        description: Places Menu
    r:
        description: Replies to a whisper
    socket:
        description: Replies to a whisper
    event:
        description: Event menu
    pp:
        description: Alias for places port
        aliases: [warp, port]
    feedback:
        description: Command for better feedback from players
    world:
        description: Command teleports player from basicWorld to world
    home:
        description: Home command
    activate:
        description: For craftcon bonuses activation
    book:
        description: Command for writableBook
    credits:
        description: Command for economy
    tell:
        description: Command for whisper
        aliases: [msg, w]
    friend:
        description: Friendlist commands
    block:
        description: Adds a player into blocklsit
    blocklist:
        description: Shows the list of blocked players
    unblock:
        description: Removes player from blocklist  
    gc:
        description: Writes into GM chat
    announce:
        description: Announces a message server-wide
    estates:
        description: Command for user regions
    book:
        description: Economy command for copying books
    jailinfo:
        description: Lets the player know when his/her jail expires
    manor:
        description: Manor commands